### ISSUE TITLE
Data understanding

### ISSUE THREAD

**Issue by ARTC-Doris** [artc-dsc/Tasks#2]
@ShiyaoBian6639 @ZengyuCao-ARTC 

Prepare [a list of questions](https://itssastar.sharepoint.com/:p:/r/sites/EsteeLauderDemandPlanning/Shared%20Documents/General/Data/ELC%20Data%20Assessment.pptx?d=wbb9e380aeabd4615a419a27d9bcfb27d&csf=1&web=1&e=YcMerW) to clarify before meeting with ELC data analytics team on 9th May.
All data and relevant docs have been uploaded to Teams Group, kindly note that the data is highly **CONFIDENTIAL**.

ELC current planning methods and KPIs:
[https://itssastar.sharepoint.com/:b:/r/sites/EsteeLauderDemandPlanning/Shared%20Documents/General/Data/Workstream%201%20-%20DP.pdf?csf=1&web=1&e=r97mob](url)

Data sources:
![Image](https://github.com/artc-dsc/Tasks/assets/136760539/146a954e-fded-4883-acaa-1218b14281d9)

**Comment by ZengyuCao-ARTC** [comment]
inserted my inputs, and split into 2 parts: planner operation & data understanding
