### ISSUE TITLE
Test backend with standardized DB

### ISSUE THREAD

**Issue by ARTC-Doris** [artc-dsc/Tasks#22]
#10 

Connect all backend endpoints to unified DB [**FusionCast**], to test if functioning well.

![Image](https://github.com/artc-dsc/Tasks/assets/136760539/8c40cab4-a006-4b5a-b73a-bff6f810e481)

**Comment by ZengyuCao-ARTC** [comment]
Updated by Zengyu 
inserted new model family to FusionCast forecast_results table 3rd May
![Capture](https://github.com/artc-dsc/Tasks/assets/136769717/524511f1-eb2f-4d45-bffe-028f63a8ed5c)

**Comment by ZengyuCao-ARTC** [comment]
updated by Zengyu on merged [forecasting_request] table: new columns for statistical module status and processing time
![image](https://github.com/artc-dsc/Tasks/assets/136769717/5b3a25c0-198a-4299-8856-0040fe956b63)
