### ISSUE TITLE
Create a centralized folder for all data sources

### ISSUE THREAD

**Issue by ARTC-Doris** [artc-dsc/Tasks#25]
**Goal:**  To have a centralized folder for all open-source dataset (could be used for benchmark model performance) 
## Format description
1. dataset folder at [DataSet](https://itssastar.sharepoint.com/:f:/r/sites/AI-FusionCastDevelopment/Shared%20Documents/General/DataSet?csf=1&web=1&e=ukXwGI)
2. All datasets to provide master information at [Dataset_compiled.xlsx](https://itssastar.sharepoint.com/:x:/r/sites/AI-FusionCastDevelopment/Shared%20Documents/General/DataSet/Dataset_compiled.xlsx?d=w95287e6993374e19b69bc3a67d13d103&csf=1&web=1&e=AHRDhv)
3. files includes at least:  
        - dataset download links & raw file (if size not big), 
        - processed files (after cleaning, mapping to the template and resampling to certain frequency)   
           formatted in "processed_xxx_<granularity>_<frequency>.csv"
        - stored in individual folders for each source
![data_source](https://github.com/artc-dsc/Tasks/assets/136769717/1f618ef9-c293-41e8-b227-7e45b8355a1c)

**Comment by ZengyuCao-ARTC** [comment]
Uploaded 2 datasets: 
- [H&M fashion transactions](https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations/data?select=transactions_train.csv)
- [product demand forecasting](https://www.kaggle.com/datasets/felixzhao/productdemandforecasting)

@ARTC-Doris  @namtuanle 
Please follow this guide to add new data source. Thanks~
