### ISSUE TITLE
Sharing finding on IHPC paper

### ISSUE THREAD

**Issue by ARTC-Doris** [artc-dsc/Tasks#3]
@namtuanle as suggested in email, please review and share finding in next bi-weekly meeting. 
Paper from IHPC on “Combined Algorithm Selection and Hyperparameter Optimization”.
[IHPC_Optimizing Demand Forecasting A Framework With Bayesian Optimization Embedded Reinforcement Learning f[1].pdf](https://github.com/artc-dsc/Tasks/files/15178912/IHPC_Optimizing.Demand.Forecasting.A.Framework.With.Bayesian.Optimization.Embedded.Reinforcement.Learning.f.1.pdf)

You can upload your slides to [Forecasting Engine Folder](https://itssastar.sharepoint.com/:f:/r/sites/AI-FusionCastDevelopment/Shared%20Documents/General/Forecasting%20Engine?csf=1&web=1&e=JxJaMW).

**Comment by ZengyuCao-ARTC** [comment]
Regarding model selection mechanism or representation learning to save computational resources, to share some literature study from my side.  Source github issue: [[Prep] Literature Review · Issue #2 · artc-dsc/AI-FusionCast-Data-Processing-Service](https://github.com/artc-dsc/AI-FusionCast-Data-Processing-Service/issues/2)

Feature Extraction ​
[Characteristic-Based-Clustering-for-Time-Series-Data.pdf](https://www.researchgate.net/profile/Rob-Hyndman/publication/220451959_Characteristic-Based_Clustering_for_Time_Series_Data/links/0912f50f5ec12b3f4d000000/Characteristic-Based-Clustering-for-Time-Series-Data.pdf) Year 2006 ​
Rule induction for forecasting method selection: meta-learning the characteristics of univariate time series​
Framework ​
[DFSeer: A Visual Analytics Approach to Facilitate Model Selection for Demand Forecasting](https://arxiv.org/pdf/2005.03244.pdf) 2020​
[AutoAI-TS: AutoAI for Time Series Forecasting](https://arxiv.org/pdf/2102.12347.pdf) Year 2021​
[AutoForecast: Automatic Time-Series Forecasting Model Selection](http://ryanrossi.com/pubs/AutoForecast-CIKM22.pdf) year 2022​
[SimpleTS: An Efficient and Universal Model Selection Framework for Time Series Forecasting](https://dl-acm-org.libproxy1.nus.edu.sg/doi/pdf/10.14778/3611540.3611561) year 2023​
[UniTS: Building a Unified Time Series Model (arxiv.org)](https://arxiv.org/pdf/2403.00131) year 2024 (add Doris's found latest one)
Retail Demand Forecast​
model selection in retail demand forecasting Year 2022 [https://www-sciencedirect-](https://www-sciencedirect-com.libproxy1.nus.edu.sg/science/article/pii/S0169207021000935)[com.libproxy1.nus.edu.sg/science/article/pii/S0169207021000935](https://www-sciencedirect-com.libproxy1.nus.edu.sg/science/article/pii/S0169207021000935)​
[retail_forecasting_review_180924_v9.2_1_.pdf](https://eprints.lancs.ac.uk/id/eprint/128587/2/retail_forecasting_review_180924_v9.2_1_.pdf)​
[Analytics for an Online Retailer - Demand Forecasting and Price Optimization at Rue La La.pdf](https://dspace.mit.edu/bitstream/handle/1721.1/101783/Analytics%20for%20an%20Online%20Retailer%20-%20Demand%20Forecasting%20and%20Price%20Optimization%20at%20Rue%20La%20La.pdf?sequence=1)​
[Demand](https://www-sciencedirect-com.libproxy1.nus.edu.sg/science/article/pii/S0169207023000134) [forecasting](https://www-sciencedirect-com.libproxy1.nus.edu.sg/science/article/pii/S0169207023000134)[ for fashion products: A systematic review](https://www-sciencedirect-com.libproxy1.nus.edu.sg/science/article/pii/S0169207023000134) Year 2016​
Meta-learning​
[Meta-learning how to forecast time series](https://robjhyndman.com/papers/fforms.pdf) year 2022​
[Meta-Learning: A Survey](https://arxiv.org/pdf/1810.03548)​
[Time series model selection with a meta-learning approach](https://eprints.soton.ac.uk/434725/1/1908.08489.pdf)

**Comment by ARTC-Doris** [comment]
[Sharing on IHPC paper](https://itssastar.sharepoint.com/:p:/r/sites/AI-FusionCastDevelopment/Shared%20Documents/General/0%20Forecasting%20Engine/Review%20on%20IHPC%20papaer.pptx?d=w1a00d20d3b2c45ea9c16c3069af8fb40&csf=1&web=1&e=iPudgE)
