### ISSUE TITLE
MVP UI Design 

### ISSUE THREAD

**Issue by ZengyuCao-ARTC** [artc-dsc/Tasks#46]
![image](https://github.com/artc-dsc/Tasks/assets/136769717/6c8e3b1f-614d-434b-85d0-f224f2294604)
![image](https://github.com/artc-dsc/Tasks/assets/136769717/ad6a9b36-e181-4212-9e19-bd296edc40fb)
I would like to highlight the target user as Data science/Domain SME

TODO 

- [ ] SKU-Fac detailed page 
- [ ] group level performance page ( will need to trace performance history)
- [ ] explainable how to show? 
- [ ] Model configuration page for SME?

**Comment by ARTC-Doris** [comment]
Approved UI/UX for [MVP](https://itssastar.sharepoint.com/:p:/r/sites/CocaCola-DemandForecasting/Shared%20Documents/General/Project%20Documents/03.%20Execution/MoM/20240729%20-%20M1%20Buy-off%20and%20PA%20proceed/AI-Powered%20Demand%20Forecasting%20Project%20-%20M1%20buy-off.pptx?d=w4e414e3fcb334ccb9320e1273f0c3d2f&csf=1&web=1&e=QrhPtp)
